### PR TITLE
Little silly changes ...

### PR DESCRIPTION
**Pull request by lguzzon**

### CODE REVIEW

**Comment by ahnick** [comment]
Hi @lguzzon.  Thanks for the PR.  I think these are all good changes.  There are some minor adjustments that I would like you to make to the PR before we merge and I have left comments on the corresponding lines.

**Comment by lguzzon** [comment]
> Hi @lguzzon. Thanks for the PR. I think these are all good changes. There are some minor adjustments that I would like you to make to the PR before we merge and I have left comments on the corresponding lines.

Thanks, but I can't find any comments on lines ... I'm wrong or what?

**Comment by lguzzon** [comment]
Done!!!

**Comment by ahnick** [comment]
@lguzzon Great thanks!  Merged. :-)

**Pull request merged**
